#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
    systemctl daemon-reload >/dev/null 2>&1 || true
fi

if [ "$1" = "purge" ]; then
    rm -rf /var/log/goinfer /var/lib/goinfer
    userdel goinfer >/dev/null 2>&1 || true
    groupdel goinfer >/dev/null 2>&1 || true
fi
